imports:
    - { resource: "@ToroCmsBundle/Resources/config/app/mysql.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/sylius_theme.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/fixtures/pages.yml" }
