imports:
    - { resource: "@ToroCmsBundle/Resources/config/app/mysql.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/sylius_resource.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/sylius_theme.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/sylius_taxonomy.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/stof_doctrine_extensions.yml" }
    - { resource: "@ToroCmsBundle/Resources/config/app/fixtures/pages.yml" }

doctrine:
    orm:
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    SyliusResourceBundle:
                        type: annotation
                        prefix: Sylius\Bundle\ResourceBundle\Model
                        dir: Model
                        is_bundle: true

doctrine_cache:
    aliases:
        analytic_share_cache: analytic_share_cache

    providers:
        analytic_share_cache:
            type: apcu
            namespace: analytic_share_cache
            aliases:
                - analytic_share_cache
